// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	entities "christhianguevara/songs-search-exercise/domain/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SongsService is an autogenerated mock type for the SongsService type
type SongsService struct {
	mock.Mock
}

// Search provides a mock function with given fields: _a0, _a1
func (_m *SongsService) Search(_a0 context.Context, _a1 *entities.SearchParams) ([]entities.Song, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []entities.Song
	if rf, ok := ret.Get(0).(func(context.Context, *entities.SearchParams) []entities.Song); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Song)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entities.SearchParams) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSongsService interface {
	mock.TestingT
	Cleanup(func())
}

// NewSongsService creates a new instance of SongsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSongsService(t mockConstructorTestingTNewSongsService) *SongsService {
	mock := &SongsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
