version: "3.9"
   
services:
  web:
    build: "."
    environment:
      AUTH_KEY: token
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - "redis"
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - "web"
  redis:
    image: redis